### PR TITLE
filter

### PR DESCRIPTION
**Pull request by daymos**
@g-sam thought would pr now, since it touches index.js.

### CODE REVIEW

**Comment by g-sam** [comment]
looks good. will merge.
a few things for next attention: 
 - looks like this isn't properly hooked up to the backend. check the api spec and the handlers. ideally data should be fetched when the selection changes specific to that selection.
 - .svg isn't a good namespace (I'm using svgs too!)
 - we need a sql script that will populate the db with some relevant data. otherwise i have no idea if this actually works!

**Comment by daymos** [comment]
I was thinking of not calling the backend for the filters. Since all the data is there after the first call I can just rerender after modifying the data in the frontend. Seems less costly for the backend..
My next pull request will do just that, preserving the structure that you are using. 

I have one .sql for that, will include it in next pull request. You can use elephantsql in the meantime, there is data there.

**Comment by daymos** [comment]
but I doubt you calling your svgs classes svg, if not there is no conflict..

**Comment by g-sam** [comment]
cool. will wait for next pr to check it out.

i'm not calling it svg ..... because it's not a good name!!! you're right it doesn't matter in practice for such a small project, but i would put something less generic.

regarding the backend, again, i don't think it matters for such a small project by impression is that it would be better practice to call for only the data you need. i could be wrong about that, but i would have thought if you do want to only make one call for everthing then you shoudn't add a querystring to the url, since that designates a different resource.

**Comment by g-sam** [comment]
@daymos, i'm seeing console errors ... it's because of the get request to a location that does not exist....this is a problem because it will mess up the error handling when you add a .fail to the call. stick with one call if you like, but if so eliminate the get requests.

**Comment by daymos** [comment]
yes, that was in the next pr. The UI route for admin page doesn't take parameters, so the issue would be fixed by not requerying db. 
 
Anyways, I can change it no problem. I had this idea because to filter by topics vs by questions, the data is the same. So, switching to what you are proposing, I'll make the call twice for the same data.  That also doesn't seem best practice.

**Comment by g-sam** [comment]
no, i think you're right to have one request used for both topics and questions, at least for the moment. we could separate them but we'd need more on the backend, which doesn't seem worth it.

main thing is to either get rid of querystring from url or add a feature on the backend to serve the same page.

**Pull request merged**
