### PR TITLE
Db

### PR DESCRIPTION
**Pull request by daymos**

### CODE REVIEW

**Comment by g-sam** [comment]
beautiful

**Comment by daymos** [comment]
Is it best practise to put the data in a .sql ?

**Comment by daymos** [comment]
Is it best practice to put the data in a .sql ?

**Comment by g-sam** [comment]
as far as i know...seems to make sense. the only discussion i found was [here](http://dba.stackexchange.com/questions/69990/what-is-the-proper-way-to-store-a-full-table-of-data-outside-of-a-database-it-n)

**Comment by g-sam** [comment]
in practice we wont need to 'store' this file as we have the db precisley for that. but we would otherwise need to generate it when needed for development.

**Comment by daymos** [comment]
Sounds good

**Pull request merged**
