### PR TITLE
fix validation and login

### PR DESCRIPTION
**Pull request by g-sam**

### CODE REVIEW

**Comment by g-sam** [comment]
@daymos the deployed version at https://wales-coop-staging.herokuapp.com should now be fully functional

**Comment by g-sam** [comment]
NB views are now in different location

**Comment by daymos** [comment]
lol

**Comment by daymos** [comment]
Im getting my head around svg, there are some new concepts

**Comment by daymos** [comment]
Im also trying to use d3 with webpack. I imported it  from login.js, just for testing,  but dont have in the console there. any ideas?

**Comment by g-sam** [comment]
no it wont we be globally available (so not accessible from console) but you should be able to use it within the module you import it into, and you can console.log out of the module or use the debugger.

**Comment by daymos** [comment]
oh, I see. For the debugger, the crome dev tool or the one in the package.json scripts?

**Comment by g-sam** [comment]
the package json one is the chrome dev tool (requires chrome beta)

**Comment by daymos** [comment]
yes, I meant if it was back or front end.

**Comment by g-sam** [comment]
@daymos this fixes an issue with login, but I couldn't replicate the error you showed me yesterday. Please see if it fixes it.

**Pull request merged**
